baseURL = "https://dinosbachasblog.netlify.com/"
languageCode = "en-us"
theme = "story"
title = "Dinos Bachas Blog"
buildFuture = true

[params]
classes = ["feature-math"]

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"
